<a href="https://colab.research.google.com/github/Aashik9567/Python_AI_assignments/blob/main/food_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
  #Importing Library
import numpy as np
import pandas as pd
import random

In [4]:
# Dataset from importing
food = pd.read_csv('/content/drive/MyDrive/recommendation system/new.csv')

In [6]:
food.head()

names                name  \
0    mutton khana set    Mutton Khana Set   
1   chicken khana set   Chicken Khana Set   
2       veg khana set       Veg Khana Set   
3   thakali khana set   Thakali Khana Set   
4  chicken steam momo  Chicken steam momo   

                                         ingredients            diet  \
0  Mutton, rice, lentils, veggies, water, seasoni...  Non-Vegetarian   
1  Chicken, rice, lentils, veggies, water, season...  Non-Vegetarian   
2     Rice, lentils, veggies, water, seasonings, oil      Vegetarian   
3  Chicken, rice, lentils, veggies, water, season...  Non-Vegetarian   
4       Chicken keema, flour, water, oil, seasonings  Non-Vegetarian   

  flavor_profile       course  
0          spicy  main course  
1          spicy  main course  
2          spicy  main course  
3          spicy  main course  
4          spicy       snacks

In [5]:
food.head(25)['ingredients']

0     Mutton, rice, lentils, veggies, water, seasoni...
1     Chicken, rice, lentils, veggies, water, season...
2        Rice, lentils, veggies, water, seasonings, oil
3     Chicken, rice, lentils, veggies, water, season...
4          Chicken keema, flour, water, oil, seasonings
5          Chicken keema, flour, water, oil, seasonings
6     Chicken keema, flour, water, oil, seasonings, ...
7     Chicken keema, flour, water, oil, seasonings, ...
8                Veggies, flour, water, oil, seasonings
9                Veggies, flour, water, oil, seasonings
10      Veggies, flour, water, oil, seasonings, sessame
11               Veggies, flour, water, oil, seasonings
12            Buff keema, flour, water, oil, seasonings
13            Buff keema, flour, water, oil, seasonings
14    Buff keema, flour, water, oil, seasonings, ses...
15    Buff keema, flour, water, oil, seasonings, veg...
16          Mutton keema, flour, water, oil, seasonings
17          Mutton keema, flour, water, oil, sea

## feature selection
    ingredients
    diet
    flavor_profile
    course

In [6]:
food = food[['names','ingredients','diet','flavor_profile','course']]

In [7]:
food['flavor_profile']=food['flavor_profile'].replace(
    '-1' , random.choice(['spicy','sweet']))

In [15]:
food

names                                        ingredients  \
0      mutton khana set  [Mutton,  rice,  lentils,  veggies,  water,  s...   
1     chicken khana set  [Chicken,  rice,  lentils,  veggies,  water,  ...   
2         veg khana set  [Rice,  lentils,  veggies,  water,  seasonings...   
3     thakali khana set  [Chicken,  rice,  lentils,  veggies,  water,  ...   
4    chicken steam momo  [Chicken keema,  flour,  water,  oil,  seasoni...   
..                  ...                                                ...   
137           cappucino                       [Milk, coffee powder, sugar]   
138               lassi   [Yoghurt, cream, dry fruits, rose water, fruits]   
139         soda drinks                                     [Water, sugar]   
140         badam shake                [Dry fruits, yoghurt, sugar, water]   
141            iced tea                          [Ice, mint leaves, sugar]   

               diet flavor_profile       course  
0    Non-Vegetarian          spicy  main course  
1    Non-Vegetarian          spicy  main course  
2        Vegetarian          spicy  main course  
3    Non-Vegetarian          spicy  main course  
4    Non-Vegetarian          spicy       snacks  
..              ...            ...          ...  
137      Vegetarian          sweet       drinks  
138      Vegetarian          sweet       drinks  
139      Vegetarian          sweet       drinks  
140      Vegetarian          sweet       drinks  
141      Vegetarian          sweet       drinks  

[142 rows x 5 columns]

In [8]:
food['flavor_profile'].value_counts()


flavor_profile
spicy    127
sweet      8
plain      7
Name: count, dtype: int64

In [9]:
food.isnull()

names  ingredients   diet  flavor_profile  course
0    False        False  False           False   False
1    False        False  False           False   False
2    False        False  False           False   False
3    False        False  False           False   False
4    False        False  False           False   False
..     ...          ...    ...             ...     ...
137  False        False  False           False   False
138  False        False  False           False   False
139  False        False  False           False   False
140  False        False  False           False   False
141  False        False  False           False   False

[142 rows x 5 columns]

In [10]:
def Convert(string):
    li = (string.split(","))
    return li

food['ingredients']=food['ingredients'].apply(Convert)
food['ingredients']


0      [Mutton,  rice,  lentils,  veggies,  water,  s...
1      [Chicken,  rice,  lentils,  veggies,  water,  ...
2      [Rice,  lentils,  veggies,  water,  seasonings...
3      [Chicken,  rice,  lentils,  veggies,  water,  ...
4      [Chicken keema,  flour,  water,  oil,  seasoni...
                             ...                        
137                         [Milk, coffee powder, sugar]
138     [Yoghurt, cream, dry fruits, rose water, fruits]
139                                       [Water, sugar]
140                  [Dry fruits, yoghurt, sugar, water]
141                            [Ice, mint leaves, sugar]
Name: ingredients, Length: 142, dtype: object

In [11]:
food['ingredients']=food['ingredients'].apply(lambda x:[i.replace(" ","") for i in x])

In [12]:
food

names                                        ingredients  \
0      mutton khana set  [Mutton, rice, lentils, veggies, water, season...   
1     chicken khana set  [Chicken, rice, lentils, veggies, water, seaso...   
2         veg khana set   [Rice, lentils, veggies, water, seasonings, oil]   
3     thakali khana set  [Chicken, rice, lentils, veggies, water, seaso...   
4    chicken steam momo      [Chickenkeema, flour, water, oil, seasonings]   
..                  ...                                                ...   
137           cappucino                        [Milk, coffeepowder, sugar]   
138               lassi     [Yoghurt, cream, dryfruits, rosewater, fruits]   
139         soda drinks                                     [Water, sugar]   
140         badam shake                 [Dryfruits, yoghurt, sugar, water]   
141            iced tea                           [Ice, mintleaves, sugar]   

               diet flavor_profile       course  
0    Non-Vegetarian          spicy  main course  
1    Non-Vegetarian          spicy  main course  
2        Vegetarian          spicy  main course  
3    Non-Vegetarian          spicy  main course  
4    Non-Vegetarian          spicy       snacks  
..              ...            ...          ...  
137      Vegetarian          sweet       drinks  
138      Vegetarian          sweet       drinks  
139      Vegetarian          sweet       drinks  
140      Vegetarian          sweet       drinks  
141      Vegetarian          sweet       drinks  

[142 rows x 5 columns]

In [13]:
food['diet']=food['diet'].apply(Convert)
food['flavor_profile']=food['flavor_profile'].apply(Convert)
food['course']=food['course'].apply(Convert)

In [14]:
food

names                                        ingredients  \
0      mutton khana set  [Mutton, rice, lentils, veggies, water, season...   
1     chicken khana set  [Chicken, rice, lentils, veggies, water, seaso...   
2         veg khana set   [Rice, lentils, veggies, water, seasonings, oil]   
3     thakali khana set  [Chicken, rice, lentils, veggies, water, seaso...   
4    chicken steam momo      [Chickenkeema, flour, water, oil, seasonings]   
..                  ...                                                ...   
137           cappucino                        [Milk, coffeepowder, sugar]   
138               lassi     [Yoghurt, cream, dryfruits, rosewater, fruits]   
139         soda drinks                                     [Water, sugar]   
140         badam shake                 [Dryfruits, yoghurt, sugar, water]   
141            iced tea                           [Ice, mintleaves, sugar]   

                 diet flavor_profile         course  
0    [Non-Vegetarian]        [spicy]  [main course]  
1    [Non-Vegetarian]        [spicy]  [main course]  
2        [Vegetarian]        [spicy]  [main course]  
3    [Non-Vegetarian]        [spicy]  [main course]  
4    [Non-Vegetarian]        [spicy]       [snacks]  
..                ...            ...            ...  
137      [Vegetarian]        [sweet]       [drinks]  
138      [Vegetarian]        [sweet]       [drinks]  
139      [Vegetarian]        [sweet]       [drinks]  
140      [Vegetarian]        [sweet]       [drinks]  
141      [Vegetarian]        [sweet]       [drinks]  

[142 rows x 5 columns]

In [15]:
food['food_name'] = food['names']
food['tags']=food['ingredients']+food['diet']+food['flavor_profile']+food['course']

In [22]:
food

names                                        ingredients  \
0      mutton khana set  [Mutton, rice, lentils, veggies, water, season...   
1     chicken khana set  [Chicken, rice, lentils, veggies, water, seaso...   
2         veg khana set   [Rice, lentils, veggies, water, seasonings, oil]   
3     thakali khana set  [Chicken, rice, lentils, veggies, water, seaso...   
4    chicken steam momo      [Chickenkeema, flour, water, oil, seasonings]   
..                  ...                                                ...   
137           cappucino                        [Milk, coffeepowder, sugar]   
138               lassi     [Yoghurt, cream, dryfruits, rosewater, fruits]   
139         soda drinks                                     [Water, sugar]   
140         badam shake                 [Dryfruits, yoghurt, sugar, water]   
141            iced tea                           [Ice, mintleaves, sugar]   

                 diet flavor_profile         course           food_name  \
0    [Non-Vegetarian]        [spicy]  [main course]    mutton khana set   
1    [Non-Vegetarian]        [spicy]  [main course]   chicken khana set   
2        [Vegetarian]        [spicy]  [main course]       veg khana set   
3    [Non-Vegetarian]        [spicy]  [main course]   thakali khana set   
4    [Non-Vegetarian]        [spicy]       [snacks]  chicken steam momo   
..                ...            ...            ...                 ...   
137      [Vegetarian]        [sweet]       [drinks]           cappucino   
138      [Vegetarian]        [sweet]       [drinks]               lassi   
139      [Vegetarian]        [sweet]       [drinks]         soda drinks   
140      [Vegetarian]        [sweet]       [drinks]         badam shake   
141      [Vegetarian]        [sweet]       [drinks]            iced tea   

                                                  tags  
0    [Mutton, rice, lentils, veggies, water, season...  
1    [Chicken, rice, lentils, veggies, water, seaso...  
2    [Rice, lentils, veggies, water, seasonings, oi...  
3    [Chicken, rice, lentils, veggies, water, seaso...  
4    [Chickenkeema, flour, water, oil, seasonings, ...  
..                                                 ...  
137  [Milk, coffeepowder, sugar, Vegetarian, sweet,...  
138  [Yoghurt, cream, dryfruits, rosewater, fruits,...  
139          [Water, sugar, Vegetarian, sweet, drinks]  
140  [Dryfruits, yoghurt, sugar, water, Vegetarian,...  
141  [Ice, mintleaves, sugar, Vegetarian, sweet, dr...  

[142 rows x 7 columns]

In [16]:
new_df=food[['food_name','tags']]
new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

<ipython-input-16-3c48003d4f6e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))


food_name                                               tags
0    mutton khana set  Mutton rice lentils veggies water seasonings o...
1   chicken khana set  Chicken rice lentils veggies water seasonings ...
2       veg khana set  Rice lentils veggies water seasonings oil Vege...
3   thakali khana set  Chicken rice lentils veggies water seasonings ...
4  chicken steam momo  Chickenkeema flour water oil seasonings Non-Ve...

In [17]:
def Convert(string):
    li = string.lower()
    return li

In [18]:
new_df['food_name']=new_df['food_name'].str.lower()

<ipython-input-18-aef15504f752>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['food_name']=new_df['food_name'].str.lower()


In [26]:
new_df

food_name                                               tags
0      mutton khana set  Mutton rice lentils veggies water seasonings o...
1     chicken khana set  Chicken rice lentils veggies water seasonings ...
2         veg khana set  Rice lentils veggies water seasonings oil Vege...
3     thakali khana set  Chicken rice lentils veggies water seasonings ...
4    chicken steam momo  Chickenkeema flour water oil seasonings Non-Ve...
..                  ...                                                ...
137           cappucino    Milk coffeepowder sugar Vegetarian sweet drinks
138               lassi  Yoghurt cream dryfruits rosewater fruits Veget...
139         soda drinks                Water sugar Vegetarian sweet drinks
140         badam shake  Dryfruits yoghurt sugar water Vegetarian sweet...
141            iced tea       Ice mintleaves sugar Vegetarian sweet drinks

[142 rows x 2 columns]

In [19]:

#####Imporint feature extractor################

import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(new_df['tags']).toarray()


print(vector)
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
  y =[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)


new_df['tags']=new_df['tags'].apply(stem)
print(new_df)
similarity = cosine_similarity(vector)
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])[1:6]
similarity[0]

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]]
              food_name                                               tags
0      mutton khana set  mutton rice lentil veggi water season oil non-...
1     chicken khana set  chicken rice lentil veggi water season oil non...
2         veg khana set  rice lentil veggi water season oil vegetarian ...
3     thakali khana set  chicken rice lentil veggi water season oil non...
4    chicken steam momo  chickenkeema flour water oil season non-vegeta...
..                  ...                                                ...
137           cappucino       milk coffeepowd sugar vegetarian sweet drink
138               lassi  yoghurt cream dryfruit rosewat fruit vegetaria...
139         soda drinks                 water sugar vegetarian sweet drink
140         badam shake  dryfruit yoghurt sugar water vegetarian sweet ...
141            iced tea          ice mintleav sugar veg

<ipython-input-19-0350125359c4>:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


array([1.        , 0.91666667, 0.91287093, 0.91666667, 0.57735027,
       0.57735027, 0.54772256, 0.63900965, 0.61237244, 0.61237244,
       0.57735027, 0.61237244, 0.57735027, 0.57735027, 0.54772256,
       0.63900965, 0.57735027, 0.57735027, 0.54772256, 0.63900965,
       0.61237244, 0.63900965, 0.63900965, 0.63900965, 0.73029674,
       0.66666667, 0.63900965, 0.45643546, 0.5       , 0.5       ,
       0.46291005, 0.5       , 0.40824829, 0.45643546, 0.38490018,
       0.36514837, 0.57735027, 0.6092718 , 0.6092718 , 0.6092718 ,
       0.6172134 , 0.6092718 , 0.69631062, 0.64549722, 0.76376262,
       0.76980036, 0.76980036, 0.76980036, 0.78334945, 0.76980036,
       0.8660254 , 0.38490018, 0.43519414, 0.43519414, 0.43519414,
       0.52223297, 0.78334945, 0.80064077, 0.80064077, 0.88070485,
       0.80064077, 0.58333333, 0.6092718 , 0.64051262, 0.64051262,
       0.6172134 , 0.64051262, 0.57735027, 0.59628479, 0.59628479,
       0.6092718 , 0.58333333, 0.64051262, 0.72057669, 0.38490

In [20]:
######OUTPUT####
def recommend(food):
    anime_index = new_df[new_df['food_name'] == food].index[0]
    distances = similarity[anime_index]
    food = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    for i in food:
        print(new_df.iloc[i[0]].food_name)
recommend('egg chowmein')

mix chowmein
chicken chowmein
buff chowmein
mutton chowmein
pork chowmein


In [27]:
recommend('chicken steam momo')

chicken fry momo
chicken jhol  momo
chicken c momo
buff steam momo
buff fry momo


In [22]:
new_df.iloc[3].name

3

In [23]:
import pickle

In [24]:
new_df=pickle.load(open("/content/drive/MyDrive/recommendation system/new_model.pkl","rb"))
similarity = pickle.load(open("/content/drive/MyDrive/recommendation system/similarity.pkl","rb"))

In [ ]:
new_food = pickle.dump(new_df,open("/content/drive/MyDrive/recommendation system/new_model.pkl",'wb'))
new_food = pickle.dump(similarity,open("/content/drive/MyDrive/recommendation system/similarity.pkl",'wb'))


In [29]:
def recommend(food):
    anime_index = new_df[new_df['food_name'] == food].index[0]
    distances = similarity[anime_index]
    food = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    print(food)
    for i in food:
        print(new_df.iloc[i[0]].food_name)

recommend('mix thukpa')
recommend('soda drinks')

[(38, 0.8864052604279182), (39, 0.8864052604279182), (41, 0.8864052604279182), (42, 0.8864052604279182), (25, 0.8486684247915054)]
egg thukpa
chicken thukpa
pork thukpa
mutton thukpa
mix chowmein
[(136, 0.9128709291752769), (140, 0.8451542547285164), (134, 0.7905694150420948), (135, 0.7905694150420948), (137, 0.7302967433402215)]
espresso
badam shake
lemon tea
milk tea
cappucino
